<a href="https://colab.research.google.com/github/ubin62/ESAA_Assignment/blob/main/YB_0904_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [20]:
import numpy as np

A = np.ones((5, 3))
B = np.ones((3, 2))

C = np.dot(A,B)

print(C)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [21]:
import numpy as np

Z = np.arange(11)

Z[(Z > 3) & (Z < 8)] *= -1

print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

파이썬과 넘파이의 차이로 결과가 다르게 나옴
- 파이썬: 내장 sum은 두 번째 인자를 초깃값(start=-1)으로 다룸
- 넘파이: 두 번째 인자를 축으로 해

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

1. Z*Z
2. 2<<Z>>2
3. Z<-Z
4.1j*Z
5. Z/1/1
6.Z<Z>Z

6번은 파이썬과 달리 np에서는 연쇄 비교 연산의 참/거짓이 모호해지므로 에러가 발생한다. (np에서는 여러 원소를 한 번에 가리킴)


#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

1. nan
2. 0
3. [-9.22337203e+18]

In [1]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)


NameError: name 'np' is not defined

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [19]:
import numpy as np

z1 = np.random.randint(0, 10, 10)
z2 = np.random.randint(0, 10, 10)

# Find common values
common_values = np.intersect1d(z1, z2)

print("z1:", z1)
print("z2:", z2)
print("Common values:", common_values)

z1: [0 6 0 0 6 4 6 9 4 2]
z2: [6 8 6 2 9 0 8 5 1 1]
Common values: [0 2 6 9]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False. nan!=1j


In [18]:
import numpy as np

print(np.sqrt(-1))
print(np.emath.sqrt(-1))
print(np.sqrt(-1) == np.emath.sqrt(-1))

nan
1j
False


/tmp/ipykernel_862/3249761414.py:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
/tmp/ipykernel_862/3249761414.py:5: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [17]:
import numpy as np

Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [16]:
A=np.random.random(5)
B=np.random.random(5)
np.add(A,B,out=B)
np.negative(A,out=A)

array([-0.54277878, -0.29992188, -0.95277892, -0.27931861, -0.33764478])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [5]:
import numpy as np

Z = np.random.uniform(0, 10, 5)
print("Original:", Z)

method1 = Z - Z % 1
method2 = Z // 1

print("Method 1 (%):", method1)
print("Method 2 (//):", method2)

Original: [0.69240259 9.60278759 8.26164766 0.7567579  8.48690318]
Method 1 (%): [0. 9. 8. 0. 8.]
Method 2 (//): [0. 9. 8. 0. 8.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [4]:
import numpy as np
z= np.zeros((5, 5)) + np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [6]:
import numpy as np

z = np.random.random(10)

z.sort()

print(z)

[0.02824346 0.08811411 0.09785948 0.10156033 0.11241107 0.15246123
 0.50318514 0.52475642 0.84666376 0.84682018]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [7]:
import numpy as np

A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

equal = np.array_equal(A, B)

print("A:", A)
print("B:", B)
print("Are equal?", equal)

A: [0 1 0 1 0]
B: [1 1 1 1 1]
Are equal? False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [8]:
import numpy as np

Z = np.random.random((10, 2))

X, Y = Z[:, 0], Z[:, 1]


R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)

print("Cartesian (X, Y):\n", Z)
print("\nPolar Radius (R):\n", R)
print("\nPolar Angle in Radians (T):\n", T)

Cartesian (X, Y):
 [[0.69742503 0.32875927]
 [0.64570182 0.06124671]
 [0.00490284 0.47351145]
 [0.78447892 0.05530751]
 [0.86065619 0.64886654]
 [0.96704709 0.5157585 ]
 [0.49922933 0.25460535]
 [0.21558125 0.87749221]
 [0.2387316  0.56665097]
 [0.81594364 0.04143591]]

Polar Radius (R):
 [0.77102809 0.64860003 0.47353684 0.78642615 1.07784825 1.09598673
 0.56040504 0.9035861  0.61488706 0.81699508]

Polar Angle in Radians (T):
 [0.44049888 0.09456998 1.56044247 0.07038576 0.64600566 0.48995736
 0.47161302 1.32988878 1.17206147 0.05073922]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [11]:
import numpy as np

Z = np.random.random(10)
print("Original vector:\n", Z)

Z[Z.argmax()] = 0

print("\nVector after replacing max value with 0:\n", Z)

Original vector:
 [0.66725315 0.17278048 0.75732069 0.17280096 0.95562649 0.21318675
 0.57972459 0.37045483 0.81798861 0.73967685]

Vector after replacing max value with 0:
 [0.66725315 0.17278048 0.75732069 0.17280096 0.         0.21318675
 0.57972459 0.37045483 0.81798861 0.73967685]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [12]:
import numpy as np

Z = np.arange(100)
v = np.random.uniform(0, 100)

index = np.abs(Z - v).argmin()

print("Scalar v:", v)
print("Closest value in Z:", Z[index])

Scalar v: 16.757836592378784
Closest value in Z: 17


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [13]:
import numpy as np

Z = np.arange(9).reshape(3, 3)

for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [14]:
import numpy as np

Z = np.random.randint(0, 10, (3, 3))
n = 1
print("Original array:\n", Z)

sorted_Z = Z[Z[:, n].argsort()]

print(f"\nSorted by column {n}:\n", sorted_Z)

Original array:
 [[1 8 8]
 [1 2 8]
 [8 9 4]]

Sorted by column 1:
 [[1 2 8]
 [1 8 8]
 [8 9 4]]
